# Generated by Django 6.1.1 on 2026-09-11 17:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('infraestructura', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Computador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_inventario', models.CharField(max_length=50, unique=True)),
                ('marca', models.CharField(blank=True, max_length=100)),
                ('modelo', models.CharField(blank=True, max_length=100)),
                ('estado', models.CharField(choices=[('OPERATIVO', 'Operativo'), ('MANTENIMIENTO', 'En mantenimiento'), ('DANADO', 'Dañado'), ('BAJA', 'De baja')], default='OPERATIVO', max_length=30)),
                ('observaciones', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('aula', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='computadores', to='infraestructura.aula')),
            ],
            options={
                'verbose_name': 'Computador',
                'verbose_name_plural': 'Computadores',
                'ordering': ['codigo_inventario'],
            },
        ),
        migrations.CreateModel(
            name='EquipoTecnologico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_inventario', models.CharField(max_length=50, unique=True)),
                ('tipo', models.CharField(choices=[('VIDEO_BEAM', 'Video Beam'), ('BARRA_SONIDO', 'Barra de sonido'), ('AIRE_ACONDICIONADO', 'Aire acondicionado'), ('TELON_PROYECCION', 'Telón de proyección')], max_length=30)),
                ('marca', models.CharField(blank=True, max_length=100)),
                ('modelo', models.CharField(blank=True, max_length=100)),
                ('serial', models.CharField(blank=True, max_length=100)),
                ('estado', models.CharField(choices=[('OPERATIVO', 'Operativo'), ('MANTENIMIENTO', 'En mantenimiento'), ('DANADO', 'Dañado'), ('BAJA', 'De baja')], default='OPERATIVO', max_length=30)),
                ('observaciones', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('aula', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='equipos_tecnologicos', to='infraestructura.aula')),
            ],
            options={
                'verbose_name': 'Equipo tecnológico',
                'verbose_name_plural': 'Equipos tecnológicos',
                'ordering': ['tipo', 'codigo_inventario'],
            },
        ),
        migrations.CreateModel(
            name='Mobiliario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_inventario', models.CharField(max_length=50, unique=True)),
                ('tipo', models.CharField(choices=[('MESA', 'Mesa'), ('SILLA', 'Silla')], max_length=20)),
                ('marca', models.CharField(blank=True, max_length=100)),
                ('modelo', models.CharField(blank=True, max_length=100)),
                ('estado', models.CharField(choices=[('BUENO', 'Bueno'), ('REGULAR', 'Regular'), ('DANADO', 'Dañado'), ('BAJA', 'De baja')], default='BUENO', max_length=30)),
                ('observaciones', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('aula', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mobiliario', to='infraestructura.aula')),
            ],
            options={
                'verbose_name': 'Elemento de mobiliario',
                'verbose_name_plural': 'Elementos de mobiliario',
                'ordering': ['tipo', 'codigo_inventario'],
            },
        ),
        migrations.CreateModel(
            name='ComponenteComputador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('CPU', 'CPU'), ('PANTALLA', 'Pantalla'), ('TECLADO', 'Teclado'), ('MOUSE', 'Mouse')], max_length=20)),
                ('marca', models.CharField(blank=True, max_length=100)),
                ('modelo', models.CharField(blank=True, max_length=100)),
                ('serial', models.CharField(blank=True, max_length=100)),
                ('estado', models.CharField(choices=[('OPERATIVO', 'Operativo'), ('MANTENIMIENTO', 'En mantenimiento'), ('DANADO', 'Dañado'), ('BAJA', 'De baja')], default='OPERATIVO', max_length=30)),
                ('observaciones', models.TextField(blank=True)),
                ('computador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='componentes', to='inventario.computador')),
            ],
            options={
                'verbose_name': 'Componente de computador',
                'verbose_name_plural': 'Componentes de computadores',
                'ordering': ['computador__codigo_inventario', 'tipo'],
                'constraints': [models.UniqueConstraint(fields=('computador', 'tipo'), name='un_componente_por_tipo')],
            },
        ),
    ]
