# Generated by Django 6.1.1 on 2026-09-14 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mobiliario',
            name='marca',
        ),
        migrations.RemoveField(
            model_name='mobiliario',
            name='modelo',
        ),
    ]
