# Generated by Django 6.1.1 on 2026-09-14 14:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('infraestructura', '0001_initial'),
        ('inventario', '0002_remove_mobiliario_marca_remove_mobiliario_modelo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MovimientoActivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('fecha', models.DateTimeField()),
                ('tipo', models.CharField(choices=[('INGRESO', 'Ingreso al inventario'), ('TRASLADO', 'Traslado'), ('SALIDA', 'Salida temporal'), ('BAJA', 'Baja'), ('REINGRESO', 'Reingreso')], max_length=20)),
                ('motivo', models.CharField(max_length=200)),
                ('observaciones', models.TextField(blank=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('aula_destino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_destino', to='infraestructura.aula')),
                ('aula_origen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_origen', to='infraestructura.aula')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contenttypes.contenttype')),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_realizados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Movimiento de activo',
                'verbose_name_plural': 'Movimientos de activos',
                'ordering': ['-fecha'],
            },
        ),
    ]
