# Generated by Django 6.1.1 on 2026-09-14 15:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('inventario', '0003_movimientoactivo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mantenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('fecha', models.DateTimeField()),
                ('tipo', models.CharField(choices=[('PREVENTIVO', 'Preventivo'), ('CORRECTIVO', 'Correctivo'), ('LIMPIEZA', 'Limpieza'), ('DIAGNOSTICO', 'Diagnóstico'), ('ACTUALIZACION', 'Actualización'), ('CAMBIO_COMPONENTE', 'Cambio de componente'), ('OTRO', 'Otro')], max_length=30)),
                ('descripcion', models.TextField()),
                ('estado_anterior', models.CharField(max_length=30)),
                ('estado_posterior', models.CharField(max_length=30)),
                ('observaciones', models.TextField(blank=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contenttypes.contenttype')),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mantenimientos_realizados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mantenimiento',
                'verbose_name_plural': 'Mantenimientos',
                'ordering': ['-fecha'],
            },
        ),
    ]
