# Generated by Django 6.1.1 on 2026-09-14 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_mantenimiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mantenimiento',
            name='estado_anterior',
            field=models.CharField(choices=[('OPERATIVO', 'Operativo'), ('MANTENIMIENTO', 'En mantenimiento'), ('DANADO', 'Dañado'), ('BAJA', 'De baja')], max_length=30),
        ),
        migrations.AlterField(
            model_name='mantenimiento',
            name='estado_posterior',
            field=models.CharField(choices=[('OPERATIVO', 'Operativo'), ('MANTENIMIENTO', 'En mantenimiento'), ('DANADO', 'Dañado'), ('BAJA', 'De baja')], max_length=30),
        ),
    ]
