# Generated by Django 6.1.1 on 2026-09-16 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0005_alter_mantenimiento_estado_anterior_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movimientoactivo',
            options={},
        ),
    ]
