# Generated by Django 6.1.1 on 2026-09-23 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0006_alter_movimientoactivo_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimientoactivo',
            name='tipo',
            field=models.CharField(choices=[('TRASLADO', 'Traslado'), ('SALIDA', 'Salida temporal'), ('BAJA', 'Baja'), ('REINGRESO', 'Reingreso')], max_length=20),
        ),
    ]
