# Generated by Django 5.2.1 on 2026-10-09 16:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0007_alter_movimientoactivo_tipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='SoftwareInstalado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('version', models.CharField(blank=True, max_length=80)),
                ('tipo_licencia', models.CharField(choices=[('LIBRE', 'Libre o gratuito'), ('INSTITUCIONAL', 'Licencia institucional'), ('COMERCIAL', 'Licencia comercial'), ('ACADEMICA', 'Licencia académica'), ('OTRO', 'Otro')], default='INSTITUCIONAL', max_length=30)),
                ('observaciones', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('computador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='software_instalado', to='inventario.computador')),
            ],
            options={
                'verbose_name': 'Software instalado',
                'verbose_name_plural': 'Software instalado',
                'ordering': ['nombre', 'computador__codigo_inventario'],
            },
        ),
    ]
