# Generated by Django 5.2.1 on 2026-10-09 16:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infraestructura', '0001_initial'),
        ('inventario', '0008_softwareinstalado'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='softwareinstalado',
            options={'ordering': ['nombre'], 'verbose_name': 'Software instalado', 'verbose_name_plural': 'Software instalado'},
        ),
        migrations.AddField(
            model_name='softwareinstalado',
            name='aula',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='software_instalado', to='infraestructura.aula'),
        ),
    ]
